### ISSUE TITLE
please help me..

### ISSUE THREAD

**Issue by JimyonYt** [DEsimas/heys-bot#1]
How do i run on replit 😭😭

**Comment by DEsimas** [comment]
You can use my deployment, it works 24/7: https://discord.com/api/oauth2/authorize?client_id=883051590959894538&permissions=0&scope=bot

Or if you want to use Replit:
1) Create new project on node.js
2) In shell terminal execute command `npm i heys-bot`
3) Paste this code in index.js:
```
const { Bot } = require("heys-bot");

const bot = new Bot({
    mongo_uri: "MONGO DB URI",
    token: "BOT TOKEN"
});

bot.start();
```
4) run application

Do you have any troubles with obtaining MONGO DB URI or BOT TOKEN?

**Comment by DEsimas** [comment]
If you need to access bot code create Repl from git repository
<img width="469" alt="2022-08-02_100046" src="https://user-images.githubusercontent.com/61614415/182312239-ca0ce32f-254f-4275-834e-b41d75f572a1.png">

When Replit ask for start command state `npm run start:dev`

On "Secrets" tab create all needed variables (MODE should be BOT)
<img width="315" alt="2022-08-02_100246" src="https://user-images.githubusercontent.com/61614415/182312948-dc8f037c-36fc-4dd5-8a9d-537e828b205d.png">
 
Use green Run button to start the bot.

**Comment by DEsimas** [comment]
**Btw this is all pointless, because Repl.it is not allowing requests to nsfw sites, only safebooru will work.**

**Comment by DEsimas** [comment]
> How do i run on replit 😭😭

How is it going?
